import {
  FaHtml5,
  FaCss3Alt,
  FaPhp,
  FaReact,
  FaNodeJs,
  FaJava,
  FaFigma,
  FaMicrosoft,
  FaCode,
  FaGoogle,
} from "react-icons/fa";
import { IoLogoJavascript } from "react-icons/io5";
import {
  SiTailwindcss,
  SiBootstrap,
  SiAdobeillustrator,
  SiCanva,
  SiGreensock,
  SiJquery,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";

export const allSkills = [
    {
      name: "HTML5",
      icon: FaHtml5,
      level: "Advanced",
      category: "Web Development",
      color: "#E34F26",
    },
    {
      name: "CSS3",
      icon: FaCss3Alt,
      level: "Advanced",
      category: "Web Development",
      color: "#1572B6",
    },
    {
      name: "JavaScript",
      icon: IoLogoJavascript,
      level: "Advanced",
      category: "Web Development",
      color: "#f0db4f",
    },
    {
      name: "PHP",
      icon: FaPhp,
      level: "Advanced",
      category: "Web Development",
      color: "#777BB4",
    },
    {
      name: "React.js",
      icon: FaReact,
      level: "Advanced",
      category: "Web Development",
      color: "#61DAFB",
    },
    {
      name: "Tailwind CSS",
      icon: SiTailwindcss,
      level: "Advanced",
      category: "UI Frameworks",
      color: "#06B6D4",
    },
    {
      name: "Bootstrap",
      icon: SiBootstrap,
      level: "Advanced",
      category: "UI Frameworks",
      color: "#7952B3",
    },
    {
      name: "Node.js",
      icon: FaNodeJs,
      level: "Intermediate",
      category: "Web Development",
      color: "#339933",
    },
    {
      name: "jQuery",
      icon: SiJquery,
      level: "Intermediate",
      category: "Web Development",
      color: "#0769AD",
    },
    {
      name: "AJAX",
      icon: FaCode,
      level: "Intermediate",
      category: "Web Development",
      color: "#0b2866",
    },
    {
      name: "React Native",
      icon: FaReact,
      level: "Intermediate",
      category: "Mobile App Development",
      color: "#61DAFB",
    },
    {
      name: "NativeWind",
      icon: FaCode,
      level: "Intermediate",
      category: "UI Frameworks",
      color: "#0b2866",
    },
    {
      name: "Java",
      icon: FaJava,
      level: "Beginner",
      category: "Programming Languages",
      color: "#ED8B00",
    },
    {
      name: "GSAP",
      icon: SiGreensock,
      level: "Beginner",
      category: "Web Development",
      color: "#88CE02",
    },
    {
      name: "C#",
      icon: TbBrandCSharp,
      level: "Beginner",
      category: "Programming Languages",
      color: "#239120",
    },
    {
      name: "Figma",
      icon: FaFigma,
      level: "Intermediate",
      category: "Prototyping & Design",
      color: "#F24E1E",
    },
    {
      name: "Canva",
      icon: SiCanva,
      level: "Advanced",
      category: "Prototyping & Design",
      color: "#00C4CC",
    },
    {
      name: "Adobe Illustrator",
      icon: SiAdobeillustrator,
      level: "Intermediate",
      category: "Prototyping & Design",
      color: "#300000",
    },
    {
      name: "Microsoft Office",
      icon: FaMicrosoft,
      level: "Advanced",
      category: "Productivity Tools",
      color: "#eb3c01",
    },
    {
      name: "Google Workspace",
      icon: FaGoogle,
      level: "Advanced",
      category: "Productivity Tools",
      color: "#4285F4",
    },
  ];